# Generated by Django 5.0.7 on 2024-08-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApi', '0002_alter_movie_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedMovie',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cinemaApi.movie')),
                ('release_date', models.DateField()),
            ],
            bases=('cinemaApi.movie',),
        ),
    ]
