# Generated by Django 5.0.7 on 2024-08-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApi', '0003_releasedmovie'),
    ]

    operations = [
    ]
