# Generated by Django 5.0.7 on 2024-08-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApi', '0004_auto_20240808_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedmovie',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
    ]
