# Generated by Django 5.0.7 on 2024-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApi', '0005_alter_releasedmovie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='now_playing',
            field=models.BooleanField(default=False),
        ),
    ]
